<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <RootNamespace>CHDSharpTestGen</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\CHDSharpLib\CHDSharpLib.csproj" />
    </ItemGroup>
    <ItemGroup></ItemGroup>
    <ItemGroup>
        <Using Include="CHDSharpTestGen.Models" />
        <Using Include="CHDSharp.Models" />
    </ItemGroup>
    <ItemGroup>
      <PackageReference Update="Meziantou.Analyzer" Version="3.0.190">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>
</Project>