<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>CHDSharpBench</RootNamespace>
    <AssemblyName>CHDSharpBench</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CHDSharpLib\CHDSharpLib.csproj" />
    <ProjectReference Include="..\CHDSharpEncoder\CHDSharpEncoder.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="CHDSharpBench.Models" />
    <Using Include="CHDSharp.Models" />
    <Using Include="CHDSharpEncoder.Models" />
    <Using Include="CHDSharpEncoder.Interfaces" />
  </ItemGroup>
</Project>