<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
        <RootNamespace>CHDSharp.BugReporting</RootNamespace>
        <AssemblyName>CHDSharp.BugReporting</AssemblyName>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Serilog" Version="4.4.0" />
    </ItemGroup>

</Project>
